### ISSUE TITLE
Correspondence to old API and php 7.0.x

### ISSUE THREAD

**Issue by fuyutsuki** [fuyutsuki/Texter#4]
### 必須項目 (Required items)

* ServerOS:

* PHP version:

* Minecraft version:

* Texter version:

* issue(s):

### TODO:
- [x] Rewrote for php7.0.x
- [x] Rewrote for old API
- [ ] Operation check <- impossible :P

**Comment by fuyutsuki** [comment]
Done
